// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHjId90gelou-fNcJ1XS18Y0ngchE04Uc',
    appId: '1:97650975609:web:d39cace923af652bf585a8',
    messagingSenderId: '97650975609',
    projectId: 'fir-flutterlearning-4e2b9',
    authDomain: 'fir-flutterlearning-4e2b9.firebaseapp.com',
    storageBucket: 'fir-flutterlearning-4e2b9.appspot.com',
    measurementId: 'G-8J9YLYSB7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08NeEW6d0gheI5u80Qj-1LX5lCLGzHUc',
    appId: '1:97650975609:android:e2739e68c6b4ff5ef585a8',
    messagingSenderId: '97650975609',
    projectId: 'fir-flutterlearning-4e2b9',
    storageBucket: 'fir-flutterlearning-4e2b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaq0-TxYxRruPzH63U5eFItgI5mmm10IQ',
    appId: '1:97650975609:ios:4db8e21dfe08e31af585a8',
    messagingSenderId: '97650975609',
    projectId: 'fir-flutterlearning-4e2b9',
    storageBucket: 'fir-flutterlearning-4e2b9.appspot.com',
    iosClientId: '97650975609-cdbbs953mo08d977vbrqe8k3he8o9p2s.apps.googleusercontent.com',
    iosBundleId: 'com.appmaking.firebaselearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaq0-TxYxRruPzH63U5eFItgI5mmm10IQ',
    appId: '1:97650975609:ios:4db8e21dfe08e31af585a8',
    messagingSenderId: '97650975609',
    projectId: 'fir-flutterlearning-4e2b9',
    storageBucket: 'fir-flutterlearning-4e2b9.appspot.com',
    iosClientId: '97650975609-cdbbs953mo08d977vbrqe8k3he8o9p2s.apps.googleusercontent.com',
    iosBundleId: 'com.appmaking.firebaselearning',
  );
}
